### ISSUE TITLE
OO numbering in MD?

### ISSUE THREAD

**Issue by eimermusic** [fletcher/Markdown.ooxsl#1]
Hi, this is not really an issue. More of a question.

Reading under [Private Notes](https://github.com/fletcher/Markdown.ooxsl#private-notes) in the readme I got the impression that OO's numbering would make it into the Markdown file... but it does not for me when I trey it out.

Is it supposed to work and broken by an update to OO?
Or am I reading too much into that section?

I had a look at the xsl files but I am not fluent in xsl and know even less about how OO export xml... in summary, I found nothing that was obviously a section dealing with numbering. :)

Very useful plugin none the less but numbering would be sweet. If is it a broken feature, please point me to where I can start poking at it. I have the motivation to fix it.

**Comment by fletcher** [comment]
Numbers are managed by your CSS/LaTeX configuration (depending on what format you ultimately end up in) - they are not included in the Markdown file itself.
