### ISSUE TITLE
Installation in OmniOutliner 4

### ISSUE THREAD

**Issue by kristopherjohnson** [fletcher/Markdown.ooxsl#2]
With OmniOutliner 4, one installs the plug-in by double-clicking the Markdown.ooxsl file, or right-clicking it and choosing Open. OmniOutliner will display a dialog asking whether to install it as a plugin, and copies it to the appropriate location (which is `~/Library/Containers/com.omnigroup.OmniOutliner4/Data/Library/Application Support/The Omni Group/OmniOutliner/Plug-Ins`).

Maybe the README.md should be updated to mention this.

**Comment by fletcher** [comment]
Omni keeps changing where plugins go, hence why I intentionally defer to them to support this.  Almost every support issue I get on this script is actually an OmniOutliner support question, not a question for me.

It's great that this works now, but who knows whether it will work in the future, or for everyone.

So the official line is still "do whatever Omni tells you to do".

;)

**Comment by yarko** [comment]
Omnioutliner support suggested dragging  Markdown.ooxsl onto  OmniOutliner 4's App icon (which also works)
